[env]
TERM = "alacritty"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 10
y = 10

[keyboard]
bindings = [{ key = "Enter", mods = "Command", action = "ToggleFullScreen" }]

# Tokyonight moon theme
[colors.primary]
background = '#222436'
foreground = '#c8d3f5'

[colors.cursor]
cursor = '#c8d3f5'
text = '#222436'

# Normal colors
[colors.normal]
black = '#1b1d2b'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#828bb8'

# Bright colors
[colors.bright]
black = '#444a73'
red = '#ff757f'
green = '#c3e88d'
yellow = '#ffc777'
blue = '#82aaff'
magenta = '#c099ff'
cyan = '#86e1fc'
white = '#c8d3f5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff966c'

[[colors.indexed_colors]]
index = 17
color = '#c53b53'

