import = ["./tokyonight.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 120
lines = 40

[keyboard]
bindings = [{ key = "Enter", mods = "Command", action = "ToggleFullScreen" }]
