theme = "rose_pine_moon"

[editor]
scrolloff = 8
line-number = "relative"
bufferline = "always"
cursorline = true
color-modes = true
rulers = [160]
shell = ["fish", "-c"]
auto-format = true
auto-completion = true
insert-final-newline = true
end-of-line-diagnostics = "hint"

[editor.statusline]
left = [
  "mode",
  "version-control",
  "file-modification-indicator",
  "read-only-indicator",
]
center = ["file-name"]
right = [
  "spinner",
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "register",
  "selections",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
auto-signature-help = true
display-inlay-hints = true
snippets = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
tabpad = "·"

[editor.indent-guides]
render = true
character = "┊" # "▏" "┊", "┆"
skip-levels = 1

[editor.gutters]
layout = ["diff", "line-numbers", "diagnostics"]

[editor.gutters.line-numbers]
min-width = 1

[editor.soft-wrap]
enable = true
max-wrap = 30
max-indent-retain = 0
wrap-at-text-width = true

[editor.smart-tab]
enable = true
supersede-menu = true

[editor.inline-diagnostics]
cursor-line = "warning"
other-lines = "info"
max-wrap = 40
max-diagnostics = 20
