theme = "tokyonight"

[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
color-modes = true
lsp.display-inlay-hints = true
rulers = [120]
shell = ["fish", "-c"]
auto-format = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
