-- Noctalia shell binds
exec(main_mod .. " + P", "noctalia msg panel-toggle launcher")
exec(main_mod .. " + SHIFT + P", "noctalia msg panel-toggle launcher /cmd")
exec(main_mod .. " + C", "noctalia msg panel-toggle control-center")
exec(main_mod .. " + V", "noctalia msg panel-toggle clipboard")
exec(main_mod .. " + O", "noctalia msg window-switcher")
exec(main_mod .. " + comma", "noctalia msg settings-toggle")
exec(main_mod .. " + period", "noctalia msg panel-toggle launcher /emo")
exec(main_mod .. " + CTRL + escape", "noctalia msg session lock")
exec(main_mod .. " + CTRL + Q", "noctalia msg panel-open session")
exec("XF86AudioPlay", "noctalia msg media toggle")
exec("XF86AudioPrev", "noctalia msg media previous")
exec("XF86AudioNext", "noctalia msg media next")
exec("XF86AudioRaiseVolume", "noctalia msg volume-up", volume_options)
exec("XF86AudioLowerVolume", "noctalia msg volume-down", volume_options)
exec("XF86AudioMute", "noctalia msg volume-mute", volume_options)
