#!/usr/bin/env bash

count=0
disconnected="睊"
wireless_connected="直"
ethernet_connected="泌"

ID="$(ip link | awk '/state UP/ {print $2}')"

while true; do
    if (ping -c 1 8.8.8.8 || ping -c 1 google.com || ping -c 1 archlinux.org) &>/dev/null; then
        if [[ $ID == e* ]]; then
            echo "$ethernet_connected" ; sleep 60
        else
            echo "$wireless_connected" ; sleep 60
        fi
    else
        echo "$disconnected" ; sleep 10
    fi
done
