{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (config.dotfiles) host;

  quote = builtins.toJSON;

  stripDesc = output: lib.removePrefix "desc:" output;

  mainOutput = stripDesc (builtins.elemAt host.monitors 0).output;
  sideOutput = stripDesc (builtins.elemAt host.monitors 1).output;

  # Niri wants the exact refresh with three decimals if specified. Omitting the
  # refresh makes it pick the highest mode for that resolution. This keeps the
  # main monitor at 4K/240Hz without depending on EDID rounding variants.
  niriMode = monitor: builtins.head (lib.splitString "@" monitor.mode);

  monitorBlock =
    monitor:
    let
      output = stripDesc monitor.output;
      position = lib.splitString "x" monitor.position;
      x = builtins.elemAt position 0;
      y = builtins.elemAt position 1;
      vrrLine = lib.optionalString ((monitor.vrr or 0) != 0) ''
        // Keep VRR on-demand to avoid OLED desktop flicker; matching windows enable it below.
        variable-refresh-rate on-demand=true
      '';
      focusLine = lib.optionalString (output == mainOutput) ''
        focus-at-startup
      '';
    in
    ''
      output ${quote output} {
          mode ${quote (niriMode monitor)}
          scale ${toString monitor.scale}
          position x=${x} y=${y}
      ${vrrLine}${focusLine}    }
    '';

  workspaceBlock = name: output: ''
    workspace ${quote name} {
        open-on-output ${quote output}
    }
  '';

  workspaceBlocks = lib.concatStrings [
    (workspaceBlock "1" sideOutput)
    (workspaceBlock "10" sideOutput)
    (workspaceBlock "2" mainOutput)
    (workspaceBlock "3" mainOutput)
    (workspaceBlock "4" mainOutput)
    (workspaceBlock "5" mainOutput)
    (workspaceBlock "6" mainOutput)
    (workspaceBlock "7" mainOutput)
    (workspaceBlock "8" mainOutput)
    (workspaceBlock "9" mainOutput)
  ];

  nvidiaEnvironment = lib.optionalString host.isNvidia ''
    LIBVA_DRIVER_NAME "nvidia"
    __GLX_VENDOR_LIBRARY_NAME "nvidia"
    NVD_BACKEND "direct"
  '';
in
{
  xdg.configFile."niri/config.kdl".text = ''
    // Generated by Home Manager: home-modules/nixos/niri.nix
    // Niri is kept alongside Hyprland and Plasma; select it from SDDM.

    ${lib.concatMapStrings monitorBlock host.monitors}

    // Persistent workspaces mirroring Hyprland:
    // 1 and 10 on the side monitor; 2-9 on the main 4K/240Hz OLED.
    ${workspaceBlocks}

    environment {
        DISPLAY ":0"
        ELECTRON_OZONE_PLATFORM_HINT "auto"
        NIXOS_OZONE_WL "1"
    ${nvidiaEnvironment}    }

    input {
        keyboard {
            xkb {
                layout "us"
                options "altwin:swap_lalt_lwin"
            }
            numlock
        }

        mouse {
            accel-speed -0.2
            accel-profile "flat"
        }

        focus-follows-mouse
        mod-key "Super"
    }

    layout {
        gaps 8
        center-focused-column "never"

        focus-ring {
            off
        }

        border {
            off
        }

        shadow {
            on
            softness 16
            spread 0
            offset x=0 y=4
            draw-behind-window true
            color "#1a1a1aee"
        }

        preset-column-widths {
            proportion 0.33333
            proportion 0.5
            proportion 0.66667
            proportion 1.0
        }

        default-column-width { proportion 1.0; }
    }

    prefer-no-csd
    screenshot-path "~/Pictures/Screenshots/Screenshot from %Y-%m-%d %H-%M-%S.png"

    hotkey-overlay {
        skip-at-startup
    }

    spawn-at-startup "systemctl" "--user" "start" "plasma-kwallet-pam.service"
    spawn-at-startup "${pkgs.kdePackages.kservice}/bin/kbuildsycoca6"
    spawn-at-startup "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1"
    spawn-at-startup "env" "-u" "QT_QPA_PLATFORMTHEME" "noctalia-shell"
    spawn-at-startup "${pkgs._1password-gui}/bin/1password" "--silent"
    spawn-at-startup "${pkgs.xwayland-satellite}/bin/xwayland-satellite" ":0"

    // Base decoration: match Hyprland's borderless, rounded look as closely as niri allows.
    window-rule {
        geometry-corner-radius 8
        clip-to-geometry true
    }

    // Hyprland uses inactive_opacity = 0.9. Keep active/media/game windows fully opaque below.
    window-rule {
        match is-active=false
        opacity 0.9
    }

    // Browsers always tile, mirroring the Hyprland chromium-browser tile rule.
    window-rule {
        match app-id="^([cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable)$"
        match app-id="^([fF]irefox|zen|librewolf)$"
        open-floating false
    }

    // Games: send to workspace 9, open fullscreen, and enable on-demand VRR.
    window-rule {
        match app-id="^(steam_app_.*|gamescope)$"
        open-on-workspace "9"
        open-fullscreen true
        opacity 1.0
        variable-refresh-rate true
    }

    // Game launchers: float, center by default, use a consistent 1200x800 size.
    window-rule {
        match app-id="^(steam|heroic|net\\.lutris\\.Lutris|com\\.usebottles\\.bottles|com\\.heroicgameslauncher\\.hgl)$"
        open-floating true
        default-column-width { fixed 1200; }
        default-window-height { fixed 800; }
        opacity 1.0
    }

    // Quick-access utilities: float and center at natural size.
    window-rule {
        match app-id="^(1password|com\\.github\\.tsowell\\.wiremix|org\\.kde\\.kcalc|gparted|transmission-gtk|org\\.pulseaudio\\.pavucontrol)$"
        match title="^(nm-connection-editor)$"
        open-floating true
    }

    // Media/creative apps: full opacity and on-demand VRR for video playback.
    window-rule {
        match app-id="^(vlc|mpv|imv|org\\.kde\\.kdenlive|com\\.obsproject\\.Studio|com\\.github\\.PintaProject\\.Pinta|zoom)$"
        opacity 1.0
        variable-refresh-rate true
    }

    // Generic dialogs and file pickers: float and use the Hyprland 800x600 default.
    window-rule {
        match app-id="^(Impala|com\\.gabm\\.satty|About|TUI\\.float|xdg-desktop-portal-gtk|sublime_text|DesktopEditors)$"
        match title="^(Open.*Files?|Open [Ff]older.*|Save.*Files?|Save.*As|Save|All Files)$"
        open-floating true
        default-column-width { fixed 800; }
        default-window-height { fixed 600; }
    }

    // Specific size overrides matching hyprland-rules.nix.
    window-rule {
        match app-id="^steam$" title="^Friends List$"
        default-column-width { fixed 300; }
        default-window-height { fixed 600; }
    }

    window-rule {
        match app-id="^gparted$"
        default-column-width { fixed 900; }
        default-window-height { fixed 700; }
    }

    window-rule {
        match app-id="^transmission-gtk$"
        default-column-width { fixed 900; }
        default-window-height { fixed 600; }
    }

    window-rule {
        match app-id="^com\\.bambulab\\.BambuStudio$"
        opacity 1.0
    }

    // Picture-in-Picture: float near the top-right, approximate Hyprland's pinned rule.
    window-rule {
        match title="^Picture-in-Picture$"
        open-floating true
        default-column-width { fixed 480; }
        default-window-height { fixed 270; }
        default-floating-position x=32 y=32 relative-to="top-right"
    }

    window-rule {
        match app-id="^Screensaver$"
        open-fullscreen true
    }

    binds {
        // Niri hotkey help overlay.
        Mod+Shift+Slash { show-hotkey-overlay; }

        // Noctalia launcher entrypoints.
        Mod+P { spawn "noctalia-shell" "ipc" "call" "launcher" "toggle"; }
        Mod+Shift+P { spawn "noctalia-shell" "ipc" "call" "launcher" "command"; }

        // App launchers and Noctalia search modes.
        Mod+Return { spawn "ghostty"; }
        Mod+B { spawn "brave"; }
        Mod+V { spawn "noctalia-shell" "ipc" "call" "launcher" "clipboard"; }
        Mod+O { spawn "noctalia-shell" "ipc" "call" "launcher" "windows"; }
        Mod+Comma { spawn "noctalia-shell" "ipc" "call" "launcher" "settings"; }
        Mod+Period { spawn "noctalia-shell" "ipc" "call" "launcher" "emoji"; }

        // Session and window management actions.
        Mod+Q { close-window; }
        Mod+Ctrl+R { spawn "niri" "msg" "action" "reload-config"; }
        Mod+Ctrl+Escape { spawn "noctalia-shell" "ipc" "call" "sessionMenu" "lock"; }
        Mod+Ctrl+Q { spawn "noctalia-shell" "ipc" "call" "sessionMenu" "toggle"; }
        Mod+T { toggle-window-floating; }
        Mod+Shift+T { switch-focus-between-floating-and-tiling; }
        Mod+F { fullscreen-window; }
        Mod+Shift+F { maximize-column; }
        Mod+Ctrl+Shift+Q { spawn "sh" "-c" "kill -9 \"$(niri msg -j focused-window | jq -r .pid)\""; }
        Mod+Shift+D { expel-window-from-column; }
        Mod+Shift+S { consume-window-into-column; }
        Mod+R { switch-preset-column-width; }
        Mod+C { center-column; }
        Mod+Ctrl+Shift+P { power-off-monitors; }
        Mod+Escape { toggle-keyboard-shortcuts-inhibit; }

        // App shortcuts.
        Mod+E { spawn "dolphin"; }
        Mod+S { spawn "bash" "-lc" "grim -g \"$(slurp)\" - | wl-copy"; }
        Print { screenshot; }
        Ctrl+Print { screenshot-screen; }
        Alt+Print { screenshot-window; }

        // Media transport keys.
        XF86AudioPlay { spawn "noctalia-shell" "ipc" "call" "media" "playPause"; }
        XF86AudioPrev { spawn "noctalia-shell" "ipc" "call" "media" "previous"; }
        XF86AudioNext { spawn "noctalia-shell" "ipc" "call" "media" "next"; }

        // Volume keys.
        XF86AudioRaiseVolume { spawn "noctalia-shell" "ipc" "call" "volume" "increase"; }
        XF86AudioLowerVolume { spawn "noctalia-shell" "ipc" "call" "volume" "decrease"; }
        XF86AudioMute { spawn "noctalia-shell" "ipc" "call" "volume" "mute"; }

        // Focus movement with vim keys and arrows.
        Mod+H { focus-column-left; }
        Mod+J { focus-window-down; }
        Mod+K { focus-window-up; }
        Mod+L { focus-column-right; }
        Mod+Left { focus-column-left; }
        Mod+Down { focus-window-down; }
        Mod+Up { focus-window-up; }
        Mod+Right { focus-column-right; }

        // Move windows/columns around the layout.
        Mod+Ctrl+H { move-column-left; }
        Mod+Ctrl+J { move-window-down; }
        Mod+Ctrl+K { move-window-up; }
        Mod+Ctrl+L { move-column-right; }
        Mod+Ctrl+Left { move-column-left; }
        Mod+Ctrl+Down { move-window-down; }
        Mod+Ctrl+Up { move-window-up; }
        Mod+Ctrl+Right { move-column-right; }

        // Resize column/window analogues to the Hyprland resize binds.
        Mod+Shift+H { set-column-width "-10%"; }
        Mod+Shift+J { set-window-height "+10%"; }
        Mod+Shift+K { set-window-height "-10%"; }
        Mod+Shift+L { set-column-width "+10%"; }
        Mod+Shift+Left { set-column-width "-10%"; }
        Mod+Shift+Down { set-window-height "+10%"; }
        Mod+Shift+Up { set-window-height "-10%"; }
        Mod+Shift+Right { set-column-width "+10%"; }

        // Monitor movement analogues.
        Mod+Alt+H { focus-monitor-left; }
        Mod+Alt+J { focus-monitor-down; }
        Mod+Alt+K { focus-monitor-up; }
        Mod+Alt+L { focus-monitor-right; }
        Mod+Alt+Left { focus-monitor-left; }
        Mod+Alt+Down { focus-monitor-down; }
        Mod+Alt+Up { focus-monitor-up; }
        Mod+Alt+Right { focus-monitor-right; }

        Mod+Ctrl+Alt+H { move-column-to-monitor-left; }
        Mod+Ctrl+Alt+J { move-column-to-monitor-down; }
        Mod+Ctrl+Alt+K { move-column-to-monitor-up; }
        Mod+Ctrl+Alt+L { move-column-to-monitor-right; }

        // First/last column helpers.
        Mod+Home { focus-column-first; }
        Mod+End { focus-column-last; }
        Mod+Ctrl+Home { move-column-to-first; }
        Mod+Ctrl+End { move-column-to-last; }

        // Workspace switching and sending columns to workspaces.
        Mod+Tab { focus-workspace-down; }
        Mod+Shift+Tab { focus-workspace-up; }
        Mod+Page_Down { focus-workspace-down; }
        Mod+Page_Up { focus-workspace-up; }
        Mod+Ctrl+Page_Down { move-column-to-workspace-down; }
        Mod+Ctrl+Page_Up { move-column-to-workspace-up; }
        Mod+Shift+Page_Down { move-workspace-down; }
        Mod+Shift+Page_Up { move-workspace-up; }
        Mod+WheelScrollDown cooldown-ms=150 { focus-workspace-down; }
        Mod+WheelScrollUp cooldown-ms=150 { focus-workspace-up; }

        Mod+1 { focus-workspace "1"; }
        Mod+2 { focus-workspace "2"; }
        Mod+3 { focus-workspace "3"; }
        Mod+4 { focus-workspace "4"; }
        Mod+5 { focus-workspace "5"; }
        Mod+6 { focus-workspace "6"; }
        Mod+7 { focus-workspace "7"; }
        Mod+8 { focus-workspace "8"; }
        Mod+9 { focus-workspace "9"; }
        Mod+0 { focus-workspace "10"; }

        Mod+Shift+1 { move-column-to-workspace "1"; }
        Mod+Shift+2 { move-column-to-workspace "2"; }
        Mod+Shift+3 { move-column-to-workspace "3"; }
        Mod+Shift+4 { move-column-to-workspace "4"; }
        Mod+Shift+5 { move-column-to-workspace "5"; }
        Mod+Shift+6 { move-column-to-workspace "6"; }
        Mod+Shift+7 { move-column-to-workspace "7"; }
        Mod+Shift+8 { move-column-to-workspace "8"; }
        Mod+Shift+9 { move-column-to-workspace "9"; }
        Mod+Shift+0 { move-column-to-workspace "10"; }
    }
  '';
}
