{
  config,
  lib,
  pkgs,
  ...
}:
let
  inherit (config.dotfiles) host;

  quote = builtins.toJSON;

  stripDesc = output: lib.removePrefix "desc:" output;

  mainOutput = stripDesc (builtins.elemAt host.monitors 0).output;
  sideOutput = stripDesc (builtins.elemAt host.monitors 1).output;
  kdlDir = ./niri;

  # Niri wants the exact refresh with three decimals if specified. Omitting the
  # refresh makes it pick the highest mode for that resolution. This keeps the
  # main monitor at 4K/240Hz without depending on EDID rounding variants.
  niriMode = monitor: builtins.head (lib.splitString "@" monitor.mode);

  monitorBlock =
    monitor:
    let
      output = stripDesc monitor.output;
      position = lib.splitString "x" monitor.position;
      x = builtins.elemAt position 0;
      y = builtins.elemAt position 1;
      vrrLine = lib.optionalString ((monitor.vrr or 0) != 0) ''
        // Keep VRR on-demand to avoid OLED desktop flicker; matching windows enable it below.
        variable-refresh-rate on-demand=true
      '';
      focusLine = lib.optionalString (output == mainOutput) ''
        focus-at-startup
      '';
    in
    ''
      output ${quote output} {
          mode ${quote (niriMode monitor)}
          scale ${toString monitor.scale}
          position x=${x} y=${y}
      ${vrrLine}${focusLine}    }
    '';

  workspaceBlock = name: output: ''
    workspace ${quote name} {
        open-on-output ${quote output}
    }
  '';

  workspaceBlocks = lib.concatStrings [
    # Side monitor anchors: workspace 1 and 10. Main uses dynamic scrolling.
    (workspaceBlock "1" sideOutput)
    (workspaceBlock "10" sideOutput)
  ];

  nvidiaEnvironment = lib.optionalString host.isNvidia ''
    LIBVA_DRIVER_NAME "nvidia"
    __GLX_VENDOR_LIBRARY_NAME "nvidia"
    NVD_BACKEND "direct"
  '';

  inputLayoutKdl = builtins.readFile (kdlDir + "/10-input-layout.kdl");
  rulesKdl = builtins.readFile (kdlDir + "/30-rules.kdl");
  bindsKdl = builtins.readFile (kdlDir + "/40-binds.kdl");

  startupBlock = ''
    spawn-at-startup "systemctl" "--user" "start" "plasma-kwallet-pam.service"
    spawn-at-startup "${pkgs.kdePackages.kservice}/bin/kbuildsycoca6"
    spawn-at-startup "${pkgs.kdePackages.polkit-kde-agent-1}/libexec/polkit-kde-authentication-agent-1"
    spawn-at-startup "${pkgs.blueman}/bin/blueman-applet"
    spawn-at-startup "env" "-u" "QT_QPA_PLATFORMTHEME" "noctalia-shell"
    spawn-at-startup "${pkgs._1password-gui}/bin/1password" "--silent"
  '';
in
{
  xdg.configFile."niri/config.kdl".text = ''
    // Generated by Home Manager: home-modules/nixos/niri.nix
    // Niri is kept alongside Hyprland and Plasma; select it from SDDM.

    ${lib.concatMapStrings monitorBlock host.monitors}

    // Side monitor anchors: workspace 1 and 10. Main monitor uses dynamic scrolling.
    ${workspaceBlocks}

    environment {
        ELECTRON_OZONE_PLATFORM_HINT "auto"
        NIXOS_OZONE_WL "1"
    ${nvidiaEnvironment}    }

    ${inputLayoutKdl}

    ${startupBlock}

    ${rulesKdl}

    ${bindsKdl}
  '';
}
